### ISSUE TITLE
Errors after update

### ISSUE THREAD

**Issue by zuevmaxim** [zuevmaxim/TutNewsBot#11]
```
2023-12-29 20:09:48,688 [ERROR  ]  Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2023-12-29 20:09:48,688 [WARNING]  Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 5496590224)
2023-12-29 20:10:00,029 [INFO   ]  Connection established (tryings = 1, bot id = 5496590224)
2023-12-29 20:14:02,105 [ERROR  ]  Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2023-12-29 20:14:02,105 [WARNING]  Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 5496590224)
2023-12-29 20:14:13,445 [INFO   ]  Connection established (tryings = 1, bot id = 5496590224)
2023-12-29 20:14:13,446 [ERROR  ]  Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2023-12-29 20:14:13,446 [WARNING]  Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 5496590224)
2023-12-29 20:14:24,951 [INFO   ]  Connection established (tryings = 1, bot id = 5496590224)
2023-12-29 20:18:37,193 [ERROR  ]  Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2023-12-29 20:18:37,194 [WARNING]  Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 5496590224)
2023-12-29 20:18:48,532 [INFO   ]  Connection established (tryings = 1, bot id = 5496590224)
```

**Comment by zuevmaxim** [comment]
```
2023-12-31 19:14:26,600 [INFO   ]  Session stopped
2023-12-31 19:14:28,809 [ERROR  ]  Cannot write to closing transport
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 625, in write_bytes
    await self.body.write(writer)
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aiohttp/multipart.py", line 906, in write
    await part.write(writer)
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aiohttp/payload.py", line 441, in write
    chunk = await self._iter.__anext__()
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aiogram/types/input_file.py", line 104, in read
    while chunk := await f.read(self.chunk_size):
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aiofiles/threadpool/utils.py", line 43, in method
    return await self._loop.run_in_executor(self._executor, cb)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/AggregatorBot/bot/notify.py", line 143, in send_message
    await bot.send_media_group(user_id, media=media_group.build())
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aiogram/client/bot.py", line 2666, in send_media_group
    return await self(call, request_timeout=request_timeout)
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aiogram/client/bot.py", line 432, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aiogram/client/session/base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aiogram/client/session/aiohttp.py", line 174, in make_request
    raw_result = await resp.text()
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1142, in text
    await self.read()
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1113, in read
    await self._wait_released()  # Underlying connection released
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1077, in _wait_released
    await self._writer
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 643, in write_bytes
    await writer.write_eof()
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aiohttp/http_writer.py", line 156, in write_eof
    self._write(chunk)
  File "/home/ec2-user/.local/lib/python3.8/site-packages/aiohttp/http_writer.py", line 75, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```

**Comment by zuevmaxim** [comment]
```
2024-01-01 06:45:19,152 [WARNING]  [scroller] Waiting for 2 seconds before continuing (required by "messages.GetReplies")
```

**Comment by zuevmaxim** [comment]
```
2024-01-02 00:10:39,763 [INFO   ]  Discarding packet: The msg_id belongs to over 300 seconds in the past. Most likely the client time has to be synchronized.
2024-01-02 00:10:39,764 [INFO   ]  Disconnected
2024-01-02 00:10:39,765 [INFO   ]  Discarding packet: The msg_id belongs to over 300 seconds in the past. Most likely the client time has to be synchronized.
2024-01-02 00:10:39,765 [INFO   ]  Disconnected
2024-01-02 00:10:39,767 [INFO   ]  Send exception: ConnectionResetError Connection lost
2024-01-02 00:10:39,767 [INFO   ]  Send exception: ConnectionResetError Connection lost
2024-01-02 00:10:39,768 [INFO   ]  Disconnected
2024-01-02 00:10:39,769 [INFO   ]  Discarding packet: The msg_id belongs to over 300 seconds in the past. Most likely the client time has to be synchronized.
```
